//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDataTables01.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class alu
    {

        [Display(Name ="Carnet")]
        public string carnet { get; set; }

        [Display(Name = "Primer Apellido")]
        public string apellido1 { get; set; }

        [Display(Name = "Segundo Apellido")]
        public string apellido2 { get; set; }

        [Display(Name = "Tercer Apellido")]
        public string apellido3 { get; set; }

        [Display(Name = "Primer Nombre")]
        public string nombre1 { get; set; }

        [Display(Name = "Segundo Nombre")]
        public string nombre2 { get; set; }

        [Display(Name = "Codio de Carrera")]
        public Nullable<int> cod_carr { get; set; }

        [Display(Name = "Alumno Activo")]
        public Nullable<int> activo { get; set; }

        [Display(Name = "Curso")]
        public Nullable<int> curso_asp { get; set; }

        [Display(Name = "Proceso")]
        public Nullable<int> proceso { get; set; }

        [Required]
        public Nullable<System.DateTime> fecha_pro { get; set; }

        [DataType(DataType.Date)]
        //[DisplayFormat(ApplyFormatInEditMode =true ,DataFormatString = "dd/mm/yyyy")]
        [Display(Name = "Fecha de Nacimiento")]
        public Nullable<System.DateTime> fecha_nac { get ; set; }

        [Display(Name = "DUI")]
        public string dui { get ; set; }
        [Display(Name = "NIT")]
        public string nit { get; set; }
        public Nullable<int> recibo_ins { get; set; }
        public Nullable<int> ciclo_in { get; set; }
        public Nullable<int> año_in { get; set; }
        public Nullable<int> cod_carr_old { get; set; }
        public string carnet_old { get; set; }
        public Nullable<bool> equi { get; set; }

        [Display(Name = "Genero")]
        public Nullable<int> sexo { get; set; }


        public override string ToString() {

            return this.nombre1 + " " + this.apellido1;

        }
        
       
    }
}
